### PR TITLE
Add STX (both 1.0 and 1.1) loader

### PR DESCRIPTION
**Pull request by RepellantMold**
Something I'd figure I'd try to add after improving the STM loader, basing the code off of both STM and S3M's loader.

### CODE REVIEW

**Comment by mrpapersonic** [comment]
build fail is unrelated, looks like libsdl.org went down

**Comment by mrpapersonic** [comment]
Since this shares a lot of code with the stm and s3m loaders the shared stuff should really be shoved into `fmt/generic.c` to prevent bitrot and diverging code between the two. The .iti, .its, and .it loaders also do that, the respective header file to put the declarations in is `include/fmt.h`.

**Comment by mrpapersonic** [comment]
Cherry-picked and applied to master, thanks!

**Comment by MesaBlack** [comment]
what's up with 11d83f8?

**Comment by mrpapersonic** [comment]
I talked with them about that privately, in that format it uses a real extended ASCII font instead of IT's own special block drawing font (try putting a ç in the sample list). ST2 uses 0xFF as the space character, so it's better to just filter it into a real space than show a useless random character.

**Pull request closed without merging**
