### PR TITLE
Fix Panning in Saving MTM feature

### PR DESCRIPTION
**Pull request by BKVad1m**
Expected behavior must have same value between 8xx and Xxx
Actual behavior: Xxx is divvied by 2 due occurs `Parameter >>= 1;`

### CODE REVIEW

**Comment by BKVad1m** [comment]
[mtmpantestAfter.zip](https://github.com/user-attachments/files/18146777/mtmpantestAfter.zip)
[MTM Pan Test.zip](https://github.com/user-attachments/files/18146810/MTM.Pan.Test.zip)

**Comment by mrpapersonic** [comment]
it actually shouldn't be using the 8xx command since it doesn't exist in MultiTracker, LOL

**Comment by BKVad1m** [comment]
> it actually shouldn't be using the 8xx command since it doesn't exist in MultiTracker, LOL

yep, this is not a original multitracker module editor effect

**Comment by mrpapersonic** [comment]
0e862f147191de41d1ac6b38f2fc17b419d2eb13 replaces the `8xx` writing with writing `E8x`

**Pull request closed without merging**
