### PR TITLE
Adlib/OPL changes and improvements

### PR DESCRIPTION
**Pull request by JosepMaJAZ**
Several fixes and improvements to the Adlib/OPL engine, including dynamic voice selection, fixes on volume and adding opl3. That last one will allow making use of stereo OPL, a feature that exists in Adlib tracker but not in ST3.

Note, Makefile.am modified, so an autoreconf -i is needed.

### CODE REVIEW

**Comment by jangler** [comment]
I was just getting jealous of stereo OPL in someone's Adlib Tracker module when I get a notification about this PR… thanks; will definitely have fun testing this out.

**Comment by JosepMaJAZ** [comment]
Oh, I haven't added yet the possibility, but it should not be more than a
couple of hours now :)

**Comment by jangler** [comment]
Is there a good way to test out the OPL3 features without hex editing a S3M? :)

**Comment by JosepMaJAZ** [comment]
An adlib song of mine done in Scream tracker 3 back in 1997. The stereo one has a slightly better kickdrum and stereo channels which can be heard in this latest commit of schismtracker.  Adlib Tracker II does not read the stereo commands of S3M modules, so there it needs to be set manually with the ZBx command.
[ADLIB stereo](http://psycle.free.fr/josepma/adlib/ADLIBRK.S3M)
[ADLIB original](http://psycle.free.fr/josepma/adlib/ADLIB.S3M)

**Comment by jangler** [comment]
Sorry for taking so long to merge this; I haven't had the chance to look at this exhaustively but from what I've checked it's Good.

**Pull request merged**
