### PR TITLE
GitHub Actions: build macOS Universal binary for aarch64 and x86_64

### PR DESCRIPTION
**Pull request by mrpapersonic**
This has *not* been tested on an actual ARM Mac.
Unfortunately, I can't test this as I don't have an M1 Mac laying around that I can use.
Anyone is welcome to make sure this functions as intended.

### CODE REVIEW

**Comment by jangler** [comment]
Any idea why that last macOS build failed?

**Comment by mrpapersonic** [comment]
Ah. It's patched in a different branch, I'll backport it rn.

**Comment by mrpapersonic** [comment]
BTW @jangler, I've been working on a "finetune" of @vcaputo's SDL2 port in the `sdl2` branch [here](https://github.com/mrpapersonic/schismtracker/tree/sdl2).
Currently, the keyboard input is just running around a "wrapper" from SDL_TEXTINPUT with some code borrowed from sdl12-compat.
(I think) the fullscreen support is more featured here, and loads correctly from config.
I haven't tested it on macOS or Windows, but they should work fine as well.

**Comment by jangler** [comment]
Nice, what's left on the roadmap for your version of the port?

**Comment by vcaputo** [comment]
Sweet!  Warm fuzzies hearing someone is making use of that branch.

**Comment by mrpapersonic** [comment]
I don't believe there's anything else left that we need to port. I'll open a PR for it.

**Pull request merged**
