### PR TITLE
vgamem-scanner: handle regular characters first

### PR DESCRIPTION
**Pull request by vcaputo**
This trivial optmization rearranges the if-else-if-else chain to
catch the most common regular characters early instead of last.

### CODE REVIEW

**Comment by vcaputo** [comment]
Not that schismtracker is CPU-bound on any of my machines, but this is an obvious optimization in what all the valgrind profiles I've seen present as the hottest function by a wide margin.

**Comment by esaruoho** [comment]
@jangler is this somewhat okay to be merged? I have no idea what it does. just wondering

**Comment by jangler** [comment]
Yeah, I didn't prioritize it since it's a small optimization. Seems fine now that I've looked at it.

**Comment by jangler** [comment]
(Thanks!)

**Pull request merged**
