### PR TITLE
fix version number calculation in STM

### PR DESCRIPTION
**Pull request by cs127**
oopsie

### CODE REVIEW

**Comment by mrpapersonic** [comment]
Maybe do the whole calculations with hex so outliers where `tmp[3] > 99` are handled properly?

**Comment by sagamusix** [comment]
Since the major version is always 2, only the minor version number is required for version checks anyway, so this whole calculation can be removed. Adjust checks accordingly (`file_version < 221` -> `file_version < 21` etc.)

**Comment by cs127** [comment]
> Since the major version is always 2, only the minor version number is required for version checks anyway, so this whole calculation can be removed. Adjust checks accordingly (`file_version < 221` -> `file_version < 21` etc.)

done

**Comment by cs127** [comment]
sorry for the messy commit history, I can redo the PR if necessary

**Pull request merged**
