### PR TITLE
Fix midi_queue_alloc() minimum audio buffer size check

### PR DESCRIPTION
**Pull request by vcaputo**

### CODE REVIEW

**Comment by vcaputo** [comment]
Only the last two commits are relevant to this PR, builds upon the rest because I added a mem_calloc() cleanup in the last commit.

**Comment by vcaputo** [comment]
rebased

**Comment by HybridDog** [comment]
l can't compile: midi-core.c:(.text+0x15e5): undefined reference to `mem_calloc'

**Comment by vcaputo** [comment]
Thanks for giving it a go!

That's odd, mem_calloc() is being used throughout the code now in master (and the CI checks have passed...)

What steps did you use to fetch and build this branch?

**Comment by vcaputo** [comment]
Here's capture of a fresh clone and fetching/checking out the branch in case you're new to git and that's where this is going awry, note this is Debian GNU/Linux x86_64:
```
foo@laptop:~$ cd /tmp
foo@laptop:/tmp$ git clone https://github.com/schismtracker/schismtracker schism
Cloning into 'schism'...
remote: Counting objects: 19678, done.
remote: Compressing objects: 100% (58/58), done.
remote: Total 19678 (delta 28), reused 30 (delta 18), pack-reused 19602
Receiving objects: 100% (19678/19678), 7.15 MiB | 166.00 KiB/s, done.
Resolving deltas: 100% (13083/13083), done.
Checking connectivity... done.
foo@laptop:/tmp$ cd schism
foo@laptop:/tmp/schism$ git remote add vcaputo https://github.com/vcaputo/schismtracker
foo@laptop:/tmp/schism$ git fetch vcaputo
remote: Counting objects: 54, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 54 (delta 45), reused 54 (delta 45), pack-reused 0
Unpacking objects: 100% (54/54), done.
From https://github.com/vcaputo/schismtracker
 * [new branch]      add_missing_log_h_includes -> vcaputo/add_missing_log_h_includes
 * [new branch]      fix_math_h_include -> vcaputo/fix_math_h_include
 * [new branch]      gitignore  -> vcaputo/gitignore
 * [new branch]      halfsize-cursor -> vcaputo/halfsize-cursor
 * [new branch]      keyboard   -> vcaputo/keyboard
 * [new branch]      loadinst_fix_keypressbug -> vcaputo/loadinst_fix_keypressbug
 * [new branch]      master     -> vcaputo/master
 * [new branch]      midi_event_dedup -> vcaputo/midi_event_dedup
 * [new branch]      midi_queue_alloc_bug -> vcaputo/midi_queue_alloc_bug
 * [new branch]      misc_cleanups -> vcaputo/misc_cleanups
 * [new branch]      plusplus   -> vcaputo/plusplus
 * [new branch]      strn_dup   -> vcaputo/strn_dup
 * [new branch]      waterfall-loop -> vcaputo/waterfall-loop
foo@laptop:/tmp/schism$ git checkout vcaputo/midi_queue_alloc_bug
Note: checking out 'vcaputo/midi_queue_alloc_bug'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at dc80b1b... schism/midi: use mem_calloc() in midi_queue_alloc()
foo@laptop:/tmp/schism$ autoreconf --install
configure.ac:36: installing './compile'
configure.ac:30: installing './install-sh'
configure.ac:30: installing './missing'
Makefile.am: installing './depcomp'
foo@laptop:/tmp/schism$ mkdir build
foo@laptop:/tmp/schism$ cd build
foo@laptop:/tmp/schism/build$ ../configure && make -j2
... snip ...
foo@laptop:/tmp/schism/build$ ls -l schismtracker
-rwxr-x--- 1 foo foo 3170192 Jun 17 10:33 schismtracker
foo@laptop:/tmp/schism/build$ ./schismtracker
```

**Comment by HybridDog** [comment]
l first applied the patch of this PR (https://github.com/schismtracker/schismtracker/pull/85.patch), then run make. After l saw that compiling didn't work l run ../configure and then make again (in the build/ folder [as documented](https://github.com/schismtracker/schismtracker/blob/master/docs/building_on_linux.md#building-schism-tracker)) and it still didn't work.

**Comment by vcaputo** [comment]
@hybriddog did you pull the latest master before applying the patch?  Because mem_calloc() *just* landed in master, so if your master is stale that may explain why this isn't linking.

**Comment by HybridDog** [comment]
l didn't, thanks, there lied the rub.
Anyway, it still crashes for me:
> schismtracker: ../schism/midi-core.c:763: midi_send_buffer: Assertion `((unsigned)pos) < ((unsigned)qlen)' failed.

**Comment by vcaputo** [comment]
Hmm, can you show us what the log viewer says so we can see what the buffer size is on your system? (Ctrl-F11)  and are you certain your build has the patch applied after you got the latest master?

I am able to reproduce the crash here and my fix certainly eliminates it on my system, seen in Ctrl-F11:
```
Using driver 'alsa'
44100 Hz, 16 bit, stereo
Buffer size: 1024 samples
```

**Comment by HybridDog** [comment]
Strangely, Ctrl+F11 doesn't work in schismtracker for me, but Ctrl+F12 and others do.
Edit: The lubuntu key combinations blocked ctrl+ F7, F10 and F11…

**Comment by vcaputo** [comment]
Maybe you can tweak your lubuntu/window manager config to not swallow those keys?

If it's annoying you could easily change the log_appendf() calls in audio_playback.c lines 1325-1327 to use printf() and capture the terminal output instead of accessing the builtin log viewer.

**Comment by HybridDog** [comment]
2017-06-17-224133_1920x1080_scrot

**Comment by vcaputo** [comment]
Thanks, that's helpful, and I suspect there's still a bug in the arithmetic which I did not closely scrutinize yet.  At a glance 10ms of 48000HZ should be 480 samples, which is less than 512, so should work unless I'm missing something.

**Comment by vcaputo** [comment]
@HybridDog I just force-pushed updates to this branch with more changes, are you willing to test?  My setup doesn't have such a small audio buffer... not that I have an actual MIDI arrangement to confirm this doesn't break things badly in other ways.  Thanks!

**Comment by vcaputo** [comment]
@jangler I'm unclear why this function even wants to deal in units of bytes at all, doesn't it make more sense to simply feed it the number of samples in the audio buffer and the samples per second, and simply always work entirely in units of samples?  Any ideas there?  why do we care about bytes per ms?

**Comment by HybridDog** [comment]
l tested it, it doesn't crash. But when l set it to output, schismtracker is very laggy.

**Comment by jangler** [comment]
@vcaputo like much of the other MIDI code in Schism, I find the original code that you touched baffling. So I have no clue.

@HybridDog yeah, that's been another complaint about Schism's MIDI (see #75). Not sure if it's directly related to this code or something else.

**Comment by vcaputo** [comment]
@sagamusix @storlek any ideas?

**Comment by vcaputo** [comment]
@HybridDog Any interest in trying out #93 on top of these changes and seeing if it fixes what you're perceiving as "laggy"?   I found that interactively playing notes for MIDI output was simply broken, but playing from patterns seems to work OK.

edit: that PR landed, so if you'd be up for simply rebuilding and seeing how this PR works for you now, feedback appreciated. Thanks

**Comment by vcaputo** [comment]
fixed some typos in commit message, nothing interesting changed.

**Comment by HybridDog** [comment]
l rebuilt and it's still lagging.

**Comment by jangler** [comment]
@HybridDog What exactly do you mean by "lag" in this context?

**Comment by HybridDog** [comment]
By lag l mean l get a low framerate and it uses much cpu (30%).

**Comment by jangler** [comment]
Hm, I can get only get Schism to use that much of a CPU core with MIDI if I'm sending 600+ new notes per second, and my CPU cores aren't even that powerful by modern standards (1.8 GHz). Even then, I don't have any framerate or UI problems…

**Comment by vcaputo** [comment]
@HybridDog would it be possible to get a `valgrind --tool=callgrind` profile of this?

Also maybe we can reproduce it by using `--audio-driver=dummy` with the dummy driver hacked to use 512 samples, since that small buffer is unique to your configuration.

**Comment by jangler** [comment]
Mine's also 512 samples. What's yours?

**Comment by vcaputo** [comment]
1024 @ 44.1Khz when on ALSA.  I wonder what's required to reproduce what HybridDog's experiencing then.

**Comment by vcaputo** [comment]
@HybridDog is this when playing a particular song, simple interactive notes/pattern editing, or even just sitting idle?

**Comment by HybridDog** [comment]
It happens when playing a song. When nothing is played, it doesn't lag.

**Comment by HybridDog** [comment]
It happens when playing a song. When nothing is played, it doesn't lag.

Here's the valgrind result: callgrind zip

**Comment by vcaputo** [comment]
Thanks for the valgrind output.

Can you confirm this lag only occurs during MIDI playback and **not** when playing files internally mixed without any MIDI output?

There's no smoking gun in the callgrind files, it all just looks like graphics rendering overhead.

**Comment by HybridDog** [comment]
> Can you confirm this lag only occurs during MIDI playback and not when playing files internally mixed without any MIDI output?

What do you mean by MIDI playback?
When setting the midi through to output (or duplex), it doesn't lag, the lag only transpires when doing it with one of the multicast/ip things.
2017-06-22-151315_1920x1056_scrot

**Comment by vcaputo** [comment]
I see, I've reproduced the lag by setting a `Multicast/IP MIDI` port to output.

Do you actually have an `IP MIDI` device you're trying to work with?

If anyone can suggest a way to end-to-end test `IP MIDI` it'd be greatly appreciated.  I've been using TiMidity++ locally exclusively for testing my changes.  If I make changes to try fix the UI latency with `IP MIDI` they'll need to be tested for correctness...

**Comment by HybridDog** [comment]
No, as far as l know, l don't have such a device.

**Comment by vcaputo** [comment]
Ok, so the lag seems to be somehow caused by the last commit added to this PR `schism/midi: fix buffer bytes per ms arithmetic`, so it appears there is significance to using there 80 instead of 100.

I'm dropping that commit, but we should still land this PR because it fixes the buffer size check making midi_queue_alloc() assert less erroneously - just not for when your buffer size is so small it's on the fringes of 10ms worth of buffer.

@HybridDog can you re-test and verify that the lag is gone with that commit dropped from this PR.  You can work around the buffer being too small instead by editing the schism config file and changing buffer_size=512 to buffer_size=1024.

**Comment by HybridDog** [comment]
l tested it and it crashed. In the config file buffer_size is set to 1024, but ctrl+f11 says 512.
When l set buffer_size to 2048 in the config file, in schismtracker it says 1024 and it doesn't crash or lag.

**Comment by jangler** [comment]
(FWIW I know zilch about multicast IP MIDI.)

**Comment by esaruoho** [comment]
would this make macosx midi more stable?

**Comment by jangler** [comment]
@esaruoho, did you test MIDI again as requested in #75? If so then please post your results there.

**Comment by esaruoho** [comment]
@jangler posted some results + examples to #75 . hope this helps! :)

**Comment by esaruoho** [comment]
@jangler hey, just saw @vcaputo post in #75 talking about this very specific pull request (#85 ) - the commentary is here: https://github.com/schismtracker/schismtracker/issues/51#issuecomment-355832908

could we try this out and see if it helps with the input/output mad-switching?

**Comment by vcaputo** [comment]
I just force-pushed a rebased version in case master had anything important since this was last touched.

**Comment by jangler** [comment]
The reason I hadn't merged this was that @HybridDog's build crashed. Has that been addressed? Or does it also crash for that reason in master, or what?

**Comment by vcaputo** [comment]
@jangler Well the PR doesn't remove the assert, so one can still have a legitimately too-small (sub 10ms) buffer.

The PR obviously fixes a bug since the 'channels' parameter is being supplied as 'audio_sample_size', not the number of channels, at the call site.  This PR fixes the parameter and variable names to reflect what's actually happening and normalizes the units to all be bytes.  Though maybe it would be preferable to normalize on samples and fix the caller to actually supply the number of channels, I haven't scrutinized the code again to see if that's the better approach.  I don't believe there's a correctness difference either way.   I can probably take a look at it later today.

**Comment by jangler** [comment]
Oh yeah, I remember looking at this. Looks fine to me and pretty much anything sane is better than what the old MIDI code does. You can still take another look if you want, but I'm just going to merge this now.

**Comment by jangler** [comment]
(Thanks! I always forget to say thanks but I really do appreciate when people contribute.)

**Pull request merged**
