### PR TITLE
Fix Haiku's save config directory

### PR DESCRIPTION
**Pull request by Begasus**
Haiku doesn't save files in ~/. directory, best to save them to ~/config/settings

### CODE REVIEW

**Comment by sagamusix** [comment]
Do you think you could look into providing either a fallback or an automatic migration for existing users, or at least showing a warning if settings are found in the old location? Seems a bit harsh that right now, people would lose all their settings when upgrading and they wouldn't know why.

**Comment by esaruoho** [comment]
@mrpapersonic what's going on with this one? :)

**Comment by sagamusix** [comment]
What's going on is: The requested fallback mechanism is still missing.

**Comment by esaruoho** [comment]
@Begasus hey could you provide the fallback or automatic migration for existing users, or show a warning if the settings are found in the old location? losing settings is not a good look.

**Comment by Begasus** [comment]
Is there any mechanisme atm available for other OS's? Could have a look first there (doing other projects atm, but could have a look around).

**Comment by mrpapersonic** [comment]
Not in the current code, no.

**Comment by sagamusix** [comment]
You could have a look at the portable mode added recently (#449), as this also causes the config dir to change at runtime.

**Comment by esaruoho** [comment]
> You could have a look at the portable mode added recently (#449), as this also causes the config dir to change at runtime.

@Begasus do you have the bandwidth to look at #449? Seems like this would be a good way to update this 3 year old PR?

**Comment by Begasus** [comment]
Checked out latest release that includes #449 , looks to be working fine as fallback (as far as my skills go) :)

**Comment by esaruoho** [comment]
@Begasus @mrpapersonic so.. what's going on with this PR , please, does it need to be merged it, can it be merged in.. should it be merged in?

**Comment by mrpapersonic** [comment]
As stated before by saga musix, there are issues here that still need to be addressed. I don't care about Haiku, so it probably won't be me finishing this PR :)

**Comment by Begasus** [comment]
Haiku is in the process on releasing a new beta, so we're a bit busy atm with getting some things up to speed, will report back later (if you can wait, if not it can be closed and we'll have it patched locally if need be) :)

**Comment by mrpapersonic** [comment]
I've implemented the fallback Saga Musix requested in 9c8cc438ee97e6903c2dc50a1d7485ad478e2b71 as part of moving to the not-so-new-anymore XDG base directory specifications.

**Pull request closed without merging**
