### PR TITLE
GitHub Release Upload for OS X and Linux (Travis)

### LINKED ISSUE #76: osx: no automatic builds?
Just saw @jangler  release https://github.com/schismtracker/schismtracker/releases/tag/20170420 only to see that there's no OSX build? Is this liable to change?

### PR DESCRIPTION
**Pull request by asbjornu**
This PR modifies `.travis.yml` to upload a `.tar.gz` file for Linux and OS X for every tag on GitHub. You can see an example of how this looks like [here](https://github.com/asbjornu/schismtracker/releases/tag/20170628).

What needs to be done before this PR starts working is replacing this gibberish:

```yaml
deploy:
  api_key:
    secure: cUAYZylRFR658zj3l5bgRptyca3wD/92byCKkFFwnuDjFHUcXX+B3qur5muzC/kx0MUO1T/3rPqtrfcDMiGshOXtJbGN+b0FjlBDr3QGpS57yb3ULzzESZmxWA4EFjrJjvw8L0nleUveAYXx7DvGQXHO6yVZ57q+A2DemfU8KtUrTWrX5Pjn9xYYhd4OBBiJ+HxLaaQLAIggAAA2k2Lt3Ah3bBkGVX2rM+YbqJ4ylbYaltW1S6GCAWDKpsR6dL6ddt1UAu+sahm2pFhWHupW/Kt8J4YNr6nS1Z7YydmPB8Cp7IJVpXK+XEtaLVEV5N/ggEIdJytfLz38dotkJ0XYjqPE8s4MSpvBzFCAHhAitH5sOXP78SzeCJHjlUN918BXhD/hYDfv1gnGRCj4WZuYxaxTPmSbemprpSLXiO31mrjBHDbqD4xylfnRaCFY6DV1afe2Zvz70/4dkoqVYZN18pWDnkF0ekQWaBTBB1xhJ744R0/7k5E5FYFF++xX5hmUtu+tawhXZoTY1LWqAwiF1UvFz+ROqJQqJtkKJzTF+L42ceBzYL5SVlIf/mJm5qV+HvcxYIj/d20qMmwReZLUe6Wir3wHxugIP6eCS2pRvnVAtzTVBuFNB7hi6r8/jtITmKJWPjXTWcuc/xhbTXoAZumKnNfTvfdeVbFRMqYRQjQ=
```
 
…with an encrypted Access Token created by someone who has ownership of the Schism Tracker repository. To create a new Access Token:

1. Go [here](https://github.com/settings/tokens).
2. Click "Generate new token".
3. Enter a description such as "automatic releases for schismtracker/schismtracker".
4. Check the `public_repo` ("Access public repositories") claim.
5. Click "Generate token".
6. Copy the generated token to an editor or some other useful place.

Now the token needs to be encrypted before it can be used in the `.travis.yml` file. To do that, the [Travis Ruby Gem](https://rubygems.org/gems/travis/versions/1.8.8) needs to be installed. Then type:

```bash
travis encrypt <token>
```

…will output the encrypted token you can use in the `.travis.yml` file.

**NB: Keep the unencrypted token, since it might provide useful for the AppVeyor version of this PR.**

This fixes the Travis part of #40 and partially fixes #76. To fully fix #76, we need to complete #42 as well.

### CODE REVIEW

**Comment by jangler** [comment]
Thank you—I meant to get on this this week but I forgot about having travel and dentistry to contend with.

**Comment by asbjornu** [comment]
@jangler: I've been meaning to do this for quite a while myself, so happy to finally find some time to get it done! Please let me know if there's anything I can do to help!

**Comment by asbjornu** [comment]
Just a note: The `.tar.gz` file needs a little adjustment. It now has parent folders which are weird and is missing the `secretly.it` file. Does that file exist within this repository somewhere? Where?

**Comment by jangler** [comment]
secretly.it isn't in the repository, no. IMO we should pull it and the DLLs from outside the repo.

**Comment by jangler** [comment]
I'm going to merge this as-is and work out the details as we go.

**Comment by asbjornu** [comment]
@jangler: Excellent!

**Pull request merged**
